name: Build and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Create Python package structure
        shell: bash
        run: |
          mkdir -p python/hfd
          cat > python/hfd/__init__.py << 'EOF'
          from .hfd import main

          __all__ = ["main"]
          EOF

      - name: Build wheels on Linux
        if: runner.os == 'Linux'
        run: |
          maturin build --release --skip-auditwheel

      - name: Build wheels on Windows/macOS
        if: runner.os != 'Linux'
        run: |
          maturin build --release

      - name: Test wheel installation (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          pip install target/wheels/*.whl
          python -c "from hfd import main"

      - name: Test wheel installation (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          pip install (Get-ChildItem target/wheels/*.whl)
          python -c "from hfd import main"

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python-version }}
          path: target/wheels/*.whl

  publish-pypi:
    name: Publish to PyPI
    needs: [build-wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Move wheels
        run: |
          mkdir -p dist/all
          find dist -type f -name "*.whl" -exec mv {} dist/all/ \;

      - name: List wheels
        run: |
          ls -la dist/all/

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine check dist/all/*
          twine upload dist/all/*

  publish-conda:
    name: Publish to Conda
    needs: [build-wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.10'

      - name: Install conda-build and anaconda-client
        shell: bash -el {0}
        run: |
          conda install -y conda-build anaconda-client

      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Move wheels
        run: |
          mkdir -p dist/all
          find dist -type f -name "*.whl" -exec mv {} dist/all/ \;

      - name: Create conda recipe
        shell: bash -el {0}
        run: |
          mkdir -p conda
          cat > conda/meta.yaml << 'EOF'
          {% set name = "hfd" %}
          {% set version = "${{ env.VERSION }}" %}
          
          package:
            name: {{ name|lower }}
            version: {{ version }}
          
          source:
            path: dist/all
          
          build:
            number: 0
            noarch: python
            script: pip install *.whl
          
          requirements:
            host:
              - python
              - pip
            run:
              - python
          
          about:
            home: https://github.com/migu/hfd
            summary: HuggingFace Dataset downloader
            license: MIT
          EOF

      - name: Build conda package
        shell: bash -el {0}
        run: |
          conda build conda
          # 显示构建目录内容，用于调试
          ls -R /usr/share/miniconda/conda-bld/

      - name: Upload to Anaconda
        shell: bash -el {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          # 添加默认通道以避免警告
          conda config --add channels defaults
          # 查找并上传构建的包
          find /usr/share/miniconda/conda-bld/ -name "*.tar.bz2" -exec anaconda -t $ANACONDA_TOKEN upload -u migu {} --force \; 