name: Build and Publish

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build-and-publish:
    name: Build and Publish to PyPI and Conda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools setuptools-rust
          pip install twine
          pip install maturin

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build wheels
        run: |
          maturin build --release --strip --compatibility manylinux2014

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload target/wheels/*

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          python-version: '3.10'

      - name: Install conda-build
        run: |
          conda install conda-build anaconda-client conda-verify -y

      - name: Build and publish to Conda
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          conda build . --output-folder conda-bld/
          anaconda -t $ANACONDA_TOKEN upload conda-bld/linux-64/*.tar.bz2 -u migu 