name: Build and Publish
on: [push]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install maturin pytest
      shell: bash
    
    - name: Debug Info
      run: |
        pwd
        ls -la
        python --version
        rustc --version
        cargo --version
      shell: bash
    
    - name: Build wheels
      run: |
        maturin build --release
      shell: bash
    
    - name: Run tests
      run: |
        cargo test --verbose
      shell: bash
    
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: target/wheels/*.whl

  publish:
    needs: build
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist
          
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install --upgrade twine
          twine upload dist/**/*.whl
